<template><div class="page"><h2 class="title">产品碳足迹</h2>
<div class="toolbar"><select v-model="model" @change="load" class="sel"><option>DV-15</option><option>DV-22</option><option>DV-37</option></select></div>
<div v-if="data" class="kpi-row"><div class="kpi-card"><div class="kl">产品型号</div><div class="kv" style="font-size:18px">{{data.product_model}}</div></div><div class="kpi-card"><div class="kl">碳足迹</div><div class="kv">{{data.footprint_kgco2}} kgCO2/台</div></div><div class="kpi-card"><div class="kl">日产量</div><div class="kv">{{data.units_produced}} 台</div></div></div>
<div v-if="data" class="section"><h3>全链条碳足迹</h3><div ref="bar" style="height:300px"></div><table style="margin-top:12px"><thead><tr><th>阶段</th><th>CO2(kg)</th><th>占比</th></tr></thead><tbody><tr v-for="x in data.breakdown" :key="x.stage"><td>{{x.stage}}</td><td>{{x.co2_kg}}</td><td>{{x.ratio}}%</td></tr></tbody></table></div>
<div v-else class="loading">加载中...</div></div></template>
<script setup>import { ref,onMounted,nextTick } from 'vue';import * as e from 'echarts';import { useEnergyStore } from '../store/energy'
const store=useEnergyStore(),model=ref('DV-15'),data=ref(null),bar=ref(null)
async function load(){ data.value=await store.fetchJSONRaw('/api/carbon/product_footprint?product_model='+model.value); nextTick(()=>{ if(data.value?.breakdown){ const ch=e.init(bar.value); ch.setOption({tooltip:{trigger:'axis'},xAxis:{type:'category',data:data.value.breakdown.map(x=>x.stage)},yAxis:{type:'value',name:'kgCO2'},series:[{type:'bar',data:data.value.breakdown.map((x,i)=>({value:x.co2_kg,itemStyle:{color:['#0d7377','#0d9488','#4da6ff','#a78bfa'][i]}})),barWidth:40,label:{show:true,position:'top',formatter:'{c}kg'}}]})}}) }
onMounted(load)</script>
<style scoped>.page{display:flex;flex-direction:column;gap:16px}.title{font-size:18px;color:#333}.toolbar{display:flex;gap:10px;background:#fff;padding:12px 16px;border-radius:10px;border:1px solid #e8eaed}.sel{padding:6px 10px;border:1px solid #ddd;border-radius:6px}.kpi-row{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.kpi-card{background:#fff;border:1px solid #e8eaed;border-radius:10px;padding:18px;text-align:center}.kl{font-size:12px;color:#999}.kv{font-size:24px;font-weight:700;color:#333;margin-top:6px}.section{background:#fff;border:1px solid #e8eaed;border-radius:10px;padding:20px}h3{font-size:14px;color:#555;margin-bottom:12px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:8px 10px;border-bottom:1px solid #f0f0f0}th{background:#f5f7fa;color:#666}.loading{text-align:center;padding:60px;color:#aaa}</style>